### ISSUE TITLE
有些环境下构建工具失效

### ISSUE THREAD

**Issue by Lanbasara** [zwfun/zw-cli#1]
尊敬的作者您好，在使用的过程中，发现有些电脑无法完成构建，报错为
C:\Users\LiuXin\AppData\Roaming\npm\node_modules\build-react-middle-end\bin\build-react-middle-end:44
        if (err) throw err;
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\LiuXin\Desktop\frontTest\hello\package.json'

不知能否解决

**Comment by zwfun** [comment]
从描述来看跟本身的脚手架无关
